### ISSUE TITLE
Controller Triggers not recognized when pressed

### ISSUE THREAD

**Issue by TeknoGodz** [FWGS/xash3d-android-project#125] opened 2016-12-14 22:49 UTC
Hi I'm trying to use my steelseries stratus xl controller and I'm having a problem with the L2 an R2 triggers.  

Inn the latest version they're supposed to be seen as axis an converted to a button for use in tree in game configuration menu.. it's not working for this controller i guess. 

I've tried both version 1.81 an 1.8 so before and after the axis to button change, so im thinking the app isn't seeing those as axis' s in the first place. 

I've tried modifying the gamecontrollerdb.txt in every way i can think of, setting the triggers as a4- 6, b whatever, all sorts of shit, just can't get it working. 

Sorry about the grammar,  I'm on android

**Comment by TeknoGodz** [comment] 2016-12-15 04:32
Also should note the triggers work fine in  other apps and emulators

**Comment by a1batross** [comment] 2016-12-15 07:15
gamecontrollerdb is not actual anymore.

Install 0.18.1, go to the keyboard menu and try to bind triggers as a keys.

If it not works, then maybe your Android device not suppports your gamepad.

15 дек. 2016 г. 1:49 AM пользователь "TeknoGodz" <notifications@github.com>
написал:

**Comment by TeknoGodz** [comment] 2016-12-15 07:19
I've tried binding in the menu and tree controller works perfectly fine with other games and emulators

**Comment by TeknoGodz** [comment] 2016-12-16 21:18
Any ideas? I know the controller works,  it works great in emulators and other games

It just seems like your app will only work properly with the 10 or so controllers actually mapped by android in keylayout files in the android system usr folder

I mean you rewrote gamepad support very recently,  so you obviously Care about people with them having a great experience,  i think taking a hint from emulator apps and how they manage to recognize all buttons on ask different types of controllers,  rather than just tree standard 360 controller or bunk...

**Comment by TeknoGodz** [comment] 2016-12-16 22:26
I think this specific controller has the triggers labeled like this

L2:axis_brake+
R2:axis_gas+

Could that be part of it?

**Comment by TeknoGodz** [comment] 2016-12-19 04:45
Well got a new MOGA 2 Pro Power, and it has the same problem, triggers unable to be mapped in the configuration in game in either mode, pivot or  HID

**Comment by TeknoGodz** [comment] 2016-12-19 04:46
And it's not my device because both controllers work perfect triggers an all in other apps

**Comment by a1batross** [comment] 2016-12-19 05:13
Check controller in this app:
https://play.google.com/store/apps/details?id=com.catalyst06.gamecontrollerverifier&hl=ru

If it will work here, then it will work in Xash3D. Otherwise it's an issue
of your device
19.12.2016 7:46 пользователь "TeknoGodz" <notifications@github.com> написал:

**Comment by a1batross** [comment] 2017-08-07 16:36
Closing, as cannot reproduce.

**Closed by a1batross** 2017-08-07 16:36 UTC
