### ISSUE TITLE
App crash while loading a new map

### ISSUE THREAD

**Issue by fuzun** [FWGS/xash3d-android-project#43] opened 2015-10-23 13:54 UTC
The app crashes when a new map in the game gets loaded.

Model: Galaxy S5 Stock Rom (Android 5)
Version: Last Version (23.10.2015)
Mod: valve(Half-life)

**Comment by a1batross** [comment] 2015-10-23 15:19
Please, attach an engine.log from xash folder and 'logcat' when app is crashed.

**Comment by Fatih54102** [comment] 2015-10-23 16:52
logcat is empty and I could not find 'engine.log'. Maybe I dont have correct startup parameters like -dev ?

**Comment by a1batross** [comment] 2015-10-23 20:33
By default, Java-launcher starts engine with "-dev 3 -log" parameters. You can check it on a field "Command line arguments". If there is no anything, I recommend you write "-dev 5 -log".

logcat cannot be empty. If app is crashed, there is must be a backtrace.

**Comment by Fatih54102** [comment] 2015-10-24 13:57
I have figured it out.
The app can not access to extSdCard root folder for write on Lollipop by default so that If you enable logging or when it gets loaded, the app crashes because it can not write a log file or do some essential storage based operations to the extSdCard/xash.
The problem is that there should be a check for write access to the directory where it locates. If it fails, pop a message box.

Workaround for SD Card Users:

Create a folder called "in.celest.xash3d.hl" in "/extSdCard/Android/data"
Then move your xash folder to there.

And It will work without crashes related to storage issues.

**Comment by a1batross** [comment] 2015-10-24 15:20
I heard about this "feature" of Lollipop. 

This will be fixed in next release.

**Comment by mittorn** [comment] 2015-10-24 15:21
I think, it is not our bug, but android 5.0 restrigtion.
Using internal soorage works fine.
All we can do is to change default suggected game path.
Have you other suggections?
And /extSdCard/Android/data is bad because it removed automaticly when application uninstalled.

**Comment by Fatih54102** [comment] 2015-10-24 15:56
Maybe you can do some workaround just like the developers of ES File Manager did.

Take a look at this: http://www.androidauthority.com/lollipop-microsd-card-app-access-564168/

There might be some special APIs for this.

**Comment by a1batross** [comment] 2017-08-07 15:22
In 0.19 using non-writable storage is prohibited.

Testing engine builds introduce "RoDir" feature: connect any directory as a read-only base directory. So setting -rodir "/extsdcard/xash" in command line will force engine use read-only resources from that directory, but write config files, saverestore data somewhere else.

**Closed by a1batross** 2017-08-07 15:22 UTC
