### ISSUE TITLE
Valve intro dosent play

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [FWGS/xash3d-android-project#191] opened 2019-08-14 08:58 UTC
So I put the valve.avi with the StartupVids.txt into the media folder, then when I pressed start the intro didn't play.

**Comment by a1batross** [comment] 2019-08-14 13:08
AVI support available only for Windows for now.

**Comment by a1batross** [comment] 2019-08-14 13:09
Duplicate of https://github.com/FWGS/xash3d/issues/6

**Closed** 2019-08-14 13:09 UTC
